# Generated by Django 5.1.6 on 2025-04-24 20:40

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('img', models.ImageField(upload_to='Images', verbose_name='Image')),
                ('about', models.TextField(verbose_name='About')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone')),
                ('complete_projects', models.IntegerField(verbose_name='Projects')),
                ('github', models.URLField(verbose_name='GitHub')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('linkedin', models.URLField(verbose_name='LinkedIn')),
                ('skill1', models.CharField(max_length=100, verbose_name='Skill1')),
                ('skill2', models.CharField(max_length=100, verbose_name='Skill2')),
                ('skill3', models.CharField(max_length=100, verbose_name='Skill3')),
            ],
            options={
                'verbose_name': 'Personal Info',
                'verbose_name_plural': 'Personal Infos',
            },
        ),
    ]
