# Generated by Django 5.1.6 on 2025-04-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_personalinfo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='img2',
            field=models.ImageField(null=True, upload_to='Images', verbose_name='Image_2'),
        ),
    ]
