# Generated by Django 5.1.6 on 2025-04-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_personalinfo_img2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(verbose_name='Start Year')),
                ('end_year', models.IntegerField(verbose_name='End Year')),
                ('degree_univer', models.CharField(max_length=255, verbose_name='Degree and University')),
                ('faculty', models.CharField(max_length=255, verbose_name='Faculty')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
    ]
