# Generated by Django 5.1.6 on 2025-04-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255, verbose_name='Skill Name')),
                ('knowledge', models.IntegerField(verbose_name='Knowledge in percents')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Skills_Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255, verbose_name='Skill Name')),
                ('knowledge', models.IntegerField(verbose_name='Knowledge in percents')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience',
            field=models.CharField(max_length=255, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='univer',
            field=models.CharField(max_length=255, verbose_name='Univer'),
        ),
    ]
