# Generated by Django 5.1.6 on 2025-04-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_skills_skills_diagram_alter_experience_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_class', models.CharField(max_length=255, verbose_name='Logo Class')),
                ('service', models.CharField(max_length=255, verbose_name='Service')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AlterModelOptions(
            name='skills_diagram',
            options={'verbose_name': 'Diagram_Skill', 'verbose_name_plural': 'Diagram_Skills'},
        ),
    ]
