# Generated by Django 5.1.6 on 2025-04-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_services_alter_skills_diagram_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Image')),
                ('project', models.CharField(max_length=255, verbose_name='Project Name')),
                ('services', models.CharField(max_length=255, verbose_name='Services')),
            ],
            options={
                'verbose_name': 'Ptoject',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
