# Generated by Django 5.1.6 on 2025-04-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='About')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
