# Generated by Django 5.1.6 on 2025-04-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_footer_info_alter_contactmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_img', models.ImageField(upload_to='Images', verbose_name='Image')),
            ],
        ),
    ]
