# Generated by Django 5.1.6 on 2025-05-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_visitorip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorip',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='ip'),
        ),
        migrations.AlterField(
            model_name='visitorip',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time'),
        ),
    ]
