# Generated by Django 5.1.6 on 2025-05-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_visitorip_ip_address_alter_visitorip_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorip',
            name='timestamp',
            field=models.DateTimeField(verbose_name='time'),
        ),
    ]
