# Generated by Django 5.1.6 on 2025-05-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_visitorip_browser_visitorip_device_visitorip_os_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorJustEnterIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Ip_Address')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('browser_divice', models.TextField(verbose_name='Divice')),
            ],
        ),
        migrations.RemoveField(
            model_name='visitorip',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='visitorip',
            name='device',
        ),
        migrations.RemoveField(
            model_name='visitorip',
            name='os',
        ),
        migrations.AlterField(
            model_name='visitorip',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='ip'),
        ),
        migrations.AlterField(
            model_name='visitorip',
            name='timestamp',
            field=models.DateTimeField(verbose_name='time'),
        ),
    ]
