# Generated by Django 5.1.6 on 2025-05-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_visitorjustenterip_remove_visitorip_browser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorjustenterip',
            name='timestamp',
            field=models.DateTimeField(verbose_name='time'),
        ),
    ]
