# Generated by Django 5.1.6 on 2025-05-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_visitorjustenterip_browser_divice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitorIP',
            new_name='VisitorWriterIP',
        ),
        migrations.AlterField(
            model_name='visitorjustenterip',
            name='timestamp',
            field=models.DateTimeField(verbose_name='time'),
        ),
    ]
