# Generated by Django 5.1.6 on 2025-05-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_visitorip_visitorwriterip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorGeoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('loc', models.CharField(blank=True, help_text='Latitude,Longitude', max_length=50, null=True)),
                ('org', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
