# Generated by Django 5.1.6 on 2025-05-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_visitorgeodata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorjustenterip',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='visitorjustenterip',
            name='device',
        ),
        migrations.RemoveField(
            model_name='visitorjustenterip',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='visitorjustenterip',
            name='os',
        ),
        migrations.AddField(
            model_name='visitorgeodata',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorgeodata',
            name='device',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorgeodata',
            name='ipv4',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='visitorgeodata',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitorgeodata',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
