# Generated by Django 5.1.6 on 2025-05-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_visitorjustenterip_browser_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitorGeoData',
            new_name='VisitorData',
        ),
    ]
