# Generated by Django 5.1.6 on 2025-05-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_visitorgeodata_visitordata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitordata',
            old_name='ip',
            new_name='ip_pub',
        ),
    ]
