# Generated by Django 5.1.6 on 2025-05-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_ip_visitordata_ip_pub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitordata',
            old_name='ip_pub',
            new_name='ip',
        ),
    ]
