# Generated by Django 5.1.6 on 2025-05-05 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_ip_pub_visitordata_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitordata',
            old_name='ip',
            new_name='ipv6',
        ),
    ]
