# Generated by Django 5.1.6 on 2025-05-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_delete_visitorjustenterip'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='CV_image',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
