# Generated by Django 5.1.6 on 2025-05-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_personalinfo_cv_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='CV_image',
            field=models.ImageField(null=True, upload_to='Images', verbose_name='CV'),
        ),
    ]
