# Generated by Django 5.1.6 on 2025-05-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_personalinfo_cv_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='CV_image',
        ),
    ]
