# Generated by Django 5.1.6 on 2025-07-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_personalinfo_cv_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='CV',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='CV_PDF'),
        ),
    ]
