# Generated by Django 5.1.6 on 2025-07-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_personalinfo_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='CV',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='CV_PDF'),
        ),
    ]
