# Generated by Django 5.1.6 on 2025-07-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_personalinfo_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='CV',
        ),
    ]
