# Generated by Django 5.1.6 on 2025-08-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_personalinfo_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.CharField(max_length=10, verbose_name='End Year'),
        ),
    ]
